---
title: "Analise de Doenças Cardíacas"
format:
  html:
    embed-resources: true
    toc: true
    code-fold: true
---

# Exploração do dataset de Doenças Cardíacas

[Dataset vem desse link](https://archive.ics.uci.edu/dataset/45/heart+disease)

## Carregando Bibliotecas
```{python}
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from ucimlrepo import fetch_ucirepo 

from sklearn import tree
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from imblearn.over_sampling import RandomOverSampler
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
```

## Carregando Dataset


```{python}

# fetch dataset 
heart_disease = fetch_ucirepo(id=45) 
df = heart_disease.data.features.copy()

assert isinstance(df, pd.DataFrame)

df['target'] = heart_disease.data.targets['num']
```

## Observando Dataset

Nota-se valores numéricos com graus distintos.

```{python}
df.head(10)
```

## Entendendo features

```{python}
df = df.sort_values(by='target', ignore_index=True)

df.plot(
    y=list(df.columns),
    secondary_y=['target']
)
```

## Analisando valores nulos

Não existem muitos valores nulos.

```{python}
df[df.isna().any(axis=1)]
```

```{python}
print(f"relação 'nan/total': {(len(df[df.isna().any(axis=1)])/len(df)):0.2f}")
```

Ou seja, faz sentido excluí-los.

```{python}
sns.heatmap(df.isna())
```

```{python}
quantidade_nulos = df.isna().sum()
df = df.dropna()
```

## Analisando distribuição de classes

As classes são bem desiguais, o que torna um estudo preciso difícil.

```{python}
sns.countplot(x='target', data=df)
```

## Verificando duplicatas

Como não há nenhum campo que sirva como identificador, 
vamos presumir que a granularidade está definida por pessoas 
diferentes.

---

## Analisando matriz de correlação

```{python}
df.columns.tolist()
```

```{python}
plt.matshow(df.corr())
plt.show()
```

## Explorando outros gráficos

Gráfico de histograma:

```{python}
#sns.pairplot(df, hue="target")
df.hist(figsize=(12, 8), bins=20)
plt.tight_layout()
plt.show()
```

Gráfico de disperção:

```{python}
sns.stripplot(data=df[["age", "trestbps", "chol", "thalach", "oldpeak"]], orient="h")
plt.show()
```

```{python}
sns.stripplot(data=df.drop(columns=["age", "trestbps", "chol", "thalach", "oldpeak"]), orient="h")
plt.show()
```

Gráfico box-plot:

```{python}
sns.boxplot(data=df)
plt.show()
```

Gráfico de violino:

```{python}
sns.violinplot(data=df[["age", "trestbps", "chol"]])
plt.show()
```

---

## Preparando dataset para ML

Isso inclui normalização dos datasets usando min-max para 
por os valores entre 0 e 1 e _oversampling_ para corrigir 
desbalanço de classes.

```{python}
scaler = MinMaxScaler()

y = df['target']
x = df.drop(columns=['target'])

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    stratify=y,
    test_size=0.2,
    random_state=42
)

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

ros = RandomOverSampler(random_state=42)

x_train, y_train = ros.fit_resample(x_train, y_train)

print(y_train.value_counts())
```

## Explorando árvores de decisão

```{python}
clf = tree.DecisionTreeClassifier()
model = clf.fit(x_train, y_train)

tree.plot_tree(
	model,
    filled=True,
    feature_names=x.columns,
    class_names=True,
    max_depth=1
) 

prediction = model.predict(x_test)
print(classification_report(y_test, prediction))
```

## Explorando K-Means

```{python}
inertia = []

k_range = range(1, 11)

for k in k_range:
    model = Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            ("kmeans", KMeans(
                n_clusters=k,
                random_state=42,
                n_init="auto"
            ))
        ]
    )

    model.fit(x)

    inertia.append(
        model.named_steps["kmeans"].inertia_
    )

plt.plot(k_range, inertia, marker='o')
plt.xlabel("Número de clusters")
plt.ylabel("Inertia")
plt.title("Método do Cotovelo")
plt.show()
```

```{python}
final_model = Pipeline(
    steps=[
        ("scaler", StandardScaler()),
        ("kmeans", KMeans(
            n_clusters=3,
            random_state=42,
            n_init="auto"
        ))
    ]
)

final_model.fit(x)

scaler = StandardScaler()
scaled_x = scaler.fit_transform(x)

pca = PCA(n_components=2)
components = pca.fit_transform(scaled_x)

clusters = final_model.named_steps["kmeans"].labels_

df["cluster"] = clusters
df.head()

df.groupby("cluster").mean(numeric_only=True)

kmeans = final_model.named_steps["kmeans"]

centroids = pca.transform(
    kmeans.cluster_centers_
)

plt.figure(figsize=(8, 6))

plt.scatter(
    components[:, 0],
    components[:, 1],
    c=clusters
)

plt.scatter(
    centroids[:, 0],
    centroids[:, 1],
    s=300,
    marker="X"
)

plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("KMeans Clusters with Centroids")

plt.show()
```
